// const categoryConfigs = [
//   {
//     key: 'categories',
//     path: '/admin/categories',
//     title: 'List of Categories',
//     buttonLabel: '+ Add Category',
//     placeholder: 'Search Category...',
//     data: ['Modern', 'Classic', 'Minimalist'],
//     navigateTo: '/admin/addcategory',
//   },
//   {
//     key: 'series',
//     path: '/admin/series',
//     title: 'List of Series',
//     buttonLabel: '+ Add Series',
//     placeholder: 'Search Series...',
//     data: ['Series A', 'Series B', 'Series C'],
//     navigateTo: '/admin/addseries',
//   },
//   {
//     key: 'materials',
//     path: '/admin/materials',
//     title: 'List of Materials',
//     buttonLabel: '+ Add Material',
//     placeholder: 'Search Material...',
//     data: ['Wood', 'Ceramic', 'Vinyl'],
//     navigateTo: '/admin/addmaterial',
//   },
//   {
//     key: 'sizes',
//     path: '/admin/sizes',
//     title: 'List of Sizes',
//     buttonLabel: '+ Add Size',
//     placeholder: 'Search Size...',
//     data: ['Small', 'Medium', 'Large'],
//     navigateTo: '/admin/addsize',
//   },
//   {
//     key: 'colors',
//     path: '/admin/colors',
//     title: 'List of Colors',
//     buttonLabel: '+ Add Color',
//     placeholder: 'Search Color...',
//     data: ['Red', 'Blue', 'Green'],
//     navigateTo: '/admin/addcolor',
//   },
//   {
//     key: 'places',
//     path: '/admin/places',
//     title: 'List of Suitable Place',
//     buttonLabel: '+ Add Suitable Place',
//     placeholder: 'Search Place...',
//     data: ['Living Room', 'Kitchen', 'Bathroom'],
//     navigateTo: '/admin/addplace',
//   },
// ];

// export default categoryConfigs;
const categoryConfigs = [
  {
    key: 'categories',
    path: '/admin/categories',
    title: 'List of Categories',
    buttonLabel: '+ Add Category',
    placeholder: 'Search Category...',
    data: ['Modern', 'Classic', 'Minimalist'],
    navigateTo: '/admin/categories/add',
  },
  {
    key: 'series',
    path: '/admin/series',
    title: 'List of Series',
    buttonLabel: '+ Add Series',
    placeholder: 'Search Series...',
    data: ['Series A', 'Series B', 'Series C'],
    navigateTo: '/admin/series/add',
  },
  {
    key: 'materials',
    path: '/admin/materials',
    title: 'List of Materials',
    buttonLabel: '+ Add Material',
    placeholder: 'Search Material...',
    data: ['Wood', 'Ceramic', 'Vinyl'],
    navigateTo: '/admin/materials/add',
  },
  {
    key: 'sizes',
    path: '/admin/sizes',
    title: 'List of Sizes',
    buttonLabel: '+ Add Size',
    placeholder: 'Search Size...',
    data: ['Small', 'Medium', 'Large'],
    navigateTo: '/admin/sizes/add',
  },
  {
    key: 'colors',
    path: '/admin/colors',
    title: 'List of Colors',
    buttonLabel: '+ Add Color',
    placeholder: 'Search Color...',
    data: ['Red', 'Blue', 'Green'],
    navigateTo: '/admin/colors/add',
  },
  {
    key: 'places',
    path: '/admin/places',
    title: 'List of Suitable Place',
    buttonLabel: '+ Add Suitable Place',
    placeholder: 'Search Place...',
    data: ['Living Room', 'Kitchen', 'Bathroom'],
    navigateTo: '/admin/places/add',
  },
];

export default categoryConfigs;
